description = "A theme ported from Ivy"
features = ["blog"]
homepage = "https://ivy.yihui.name"
license = "Unlicense"
licenselink = "https://github.com/yihui/hugo-ivy/blob/master/LICENSE.md"
min_version = "0.18"
name = "Ivy"
tags = ["minimal", "blog", "personal", "clean", "simple", "minimalist"]

[author]
homepage = "https://yihui.name"
name = "Yihui Xie"

[original]
author = "dmulholland"
homepage = "http://mulholland.xyz/docs/ivy/"
repo = "https://github.com/dmulholland/ivy"

[params]
mpqrcode = "http://blogcdn.idoustudio.com/idoubi-mp.jpeg"

[params.comment]
repo = "idoubi/idoubi.cc"
theme = "github-light"
